### ISSUE TITLE
broken links when org-id linked files are on a different device/partition than the emacs config

### ISSUE THREAD

**Issue by zeeros** [kaushalmodi/ox-hugo#500]
## Actual Behavior

The following `.md` is generated

```
+++
title = "A"
draft = false
+++

[B]({{<relref "../../../../../data/Documents/rnotes/org/B.md#" >}})
```

## Expected Behavior

I'm expecting the following `.md` to be generated

```
+++
title = "A"
draft = false
+++

[B]({{<relref "B.md#" >}})
```

## How to Reproduce the Issue

Run the following `.el`

```
(require 'find-lisp)
(require 'ox-hugo)

(with-current-buffer (find-file-noselect "org/A.org")
  (setq org-hugo-base-dir "../hugo")
  (let ((org-id-extra-files (find-lisp-find-files "." "\.org$")))
    (org-hugo-export-wim-to-md)))
```

### Example Org File

The following `org` files are stored in the subfolder `org/`

```
:PROPERTIES:
:ID:       1e8ccec9-735d-41d0-b0cf-143d9c3e965d
:END:
#+title: A

[[id:01579e8c-a90b-4c53-af58-e18ff7877d00][B]]
```

```
:PROPERTIES:
:ID:       01579e8c-a90b-4c53-af58-e18ff7877d00
:END:
#+title: B
```

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

* Debug information for =ox-hugo=
** Emacs Version
#+begin_example
GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4)
 of 2021-03-26
#+end_example
** Org Version
#+begin_example
Org mode version 9.4.4 (release_9.4.4 @ /usr/share/emacs/27.2/lisp/org/)
#+end_example
** Hugo Version
#+begin_example
hugo v0.89.4+extended linux/amd64 BuildDate=unknown
#+end_example
*** Org =load-path= shadows
No Org mode shadows found in =load-path=
** =ox-hugo= defcustoms
|org-hugo-section                                      |"posts"|
|org-hugo-use-code-for-kbd                             |nil|
|org-hugo-preserve-filling                             |t|
|org-hugo-delete-trailing-ws                           |t|
|org-hugo-prefer-hyphen-in-tags                        |t|
|org-hugo-allow-spaces-in-tags                         |t|
|org-hugo-tag-processing-functions                     |(org-hugo--tag-processing-fn-replace-with-spaces-maybe org-hugo--tag-processing-fn-replace-with-hyphens-maybe)|
|org-hugo-auto-set-lastmod                             |nil|
|org-hugo-export-with-toc                              |nil|
|org-hugo-export-with-section-numbers                  |nil|
|org-hugo-front-matter-format                          |"toml"|
|org-hugo-default-static-subdirectory-for-externals    |"ox-hugo"|
|org-hugo-external-file-extensions-allowed-for-copying |("jpg" "jpeg" "tiff" "png" "svg" "gif" "mp4" "pdf" "odt" "doc" "ppt" "xls" "docx" "pptx" "xlsx")|
|org-hugo-date-format                                  |"%Y-%m-%dT%T%z"|
|org-hugo-paired-shortcodes                            |""|
|org-hugo-langs-no-descr-in-code-fences                |nil|
|org-hugo-suppress-lastmod-period                      |0.0|
|org-hugo-front-matter-format                          |"toml"|
End of buffer [3 times]
Mark set
</details>

**Comment by zeeros** [comment]
To be clear, I've been trying to follow this setup

https://github.com/jethrokuan/braindump

**Comment by kaushalmodi** [comment]
Test case

| Org file  | Exported Md | Hugo rendered HTML |
| ------------- | ------------- |---- |
| [`org-roam-file-A.org`](https://raw.githubusercontent.com/kaushalmodi/ox-hugo/main/test/site/content-org/org-roam-file-A.org)  --> | [`org-roam-file-A.md`](https://raw.githubusercontent.com/kaushalmodi/ox-hugo/main/test/site/content/org-roam/org-roam-file-A.md)  --> | [/org-roam/org-roam-file-a/](https://ox-hugo.scripter.co/test/org-roam/org-roam-file-a/)|
| [`org-roam-file-B.org`](https://raw.githubusercontent.com/kaushalmodi/ox-hugo/main/test/site/content-org/org-roam-file-B.org)  --> | [`org-roam-file-B.md`](https://raw.githubusercontent.com/kaushalmodi/ox-hugo/main/test/site/content/org-roam/org-roam-file-B.md)  --> | [/org-roam/org-roam-file-b/](https://ox-hugo.scripter.co/test/org-roam/org-roam-file-b/)|

**Comment by kaushalmodi** [comment]
Another thought: Is it possible that you cloned that repo at multiple places and the Org files from all those places get added to `org-id-extra-files`? If so, may be the ID search found the "B.org" from a different location before it found it in the current directory, and so it's pointing to that `../../../../../data/Documents/rnotes/org/B.md` path?

Alternatively, just print the value of `org-id-extra-files` and review the list of files in there.


```el
(require 'find-lisp)
(require 'ox-hugo)

(with-current-buffer (find-file-noselect "org/A.org")
  (setq org-hugo-base-dir "../hugo")
  (let ((org-id-extra-files (find-lisp-find-files "." "\.org$")))
    (message "dbg org-id-extra-files: %S" org-id-extra-files)            ;<----------------------- debug
    (org-hugo-export-wim-to-md)))
```

**Comment by zeeros** [comment]
I'm not setting `org-hugo-base-dir` through the `.dir-locals.el`, but I guess I'm getting no error because I set it in the script I call

```
(require 'find-lisp)
(require 'ox-hugo)

(with-current-buffer (find-file-noselect "org/org-roam-file-a.org")
  (setq org-hugo-base-dir "../hugo")
  (let ((org-id-extra-files (find-lisp-find-files "." "\.org$")))
    (org-hugo-export-wim-to-md)))
```

I've tried to export the [org-roam-file-a.org](https://github.com/kaushalmodi/ox-hugo/blob/4cb08af2eb9691f12a6df2ae158fe5c5b0b65f9d/test/site/content-org/org-roam-file-A.org) and the  [org-roam-file-b.org](https://github.com/kaushalmodi/ox-hugo/blob/4cb08af2eb9691f12a6df2ae158fe5c5b0b65f9d/test/site/content-org/org-roam-file-B.org) that you committed.  However, I still get the messed up path for the link

```
+++
title = "A"
tags = ["org-roam"]
categories = ["org-id"]
draft = false
+++

<https://github.com/kaushalmodi/ox-hugo/issues/500>

[B]({{<relref "../../../../../data/Documents/rnotes/org/org-roam-file-B.md#" >}})
```

**Comment by kaushalmodi** [comment]
Can you try deleting .dir-locals.el and use just the keywords based approach from the tests? i.e. use the exact tests and delete the .dir-locals.el

**Comment by zeeros** [comment]
> Another thought: Is it possible that you cloned that repo at multiple places and the Org files from all those places get added to `org-id-extra-files`? If so, may be the ID search found the "B.org" from a different location before it found it in the current directory, and so it's pointing to that `../../../../../data/Documents/rnotes/org/B.md` path?
> 
> Alternatively, just print the value of `org-id-extra-files` and review the list of files in there.
> 
> ```emacs-lisp
> (require 'find-lisp)
> (require 'ox-hugo)
> 
> (with-current-buffer (find-file-noselect "org/A.org")
>   (setq org-hugo-base-dir "../hugo")
>   (let ((org-id-extra-files (find-lisp-find-files "." "\.org$")))
>     (message "dbg org-id-extra-files: %S" org-id-extra-files)            ;<----------------------- debug
>     (org-hugo-export-wim-to-md)))
> ```

I also thought about that, but this doesn't seem the case

```
[zeeros@archeros rnotes]$ ./build.py
[1/2] org2md org/org-roam-file-B.org
dbg org-id-extra-files: ("/home/zeeros/Documents/rnotes/org/org-roam-file-B.org" "/home/zeeros/Documents/rnotes/org/org-roam-file-A.org")
[ox-hugo] Exporting ‘B’ (org-roam-file-B.org)
[2/2] org2md org/org-roam-file-A.org
dbg org-id-extra-files: ("/home/zeeros/Documents/rnotes/org/org-roam-file-B.org" "/home/zeeros/Documents/rnotes/org/org-roam-file-A.org")
[ox-hugo] Exporting ‘A’ (org-roam-file-A.org)
```

> Can you try deleting .dir-locals.el and use just the keywords based approach from the tests? i.e. use the exact tests and delete the .dir-locals.el

I've tried, but the result is the same

**Comment by kaushalmodi** [comment]
> I've tried, but the result is the same

ok, in any case, I updated the tests to use .dir-locals.el. 

Can you fetch this repo and checkout the [`org-id-path-dbg`](https://github.com/kaushalmodi/ox-hugo/tree/org-id-path-dbg) branch? Then eval ox-hugo.el and try to export the A Org file. You will see a bunch of debug messages printed.

For me they are:

```
[ox-hugo] Exporting ‘A’ (org-roam-file-A.org)
org-babel-exp process emacs-lisp at position 208...
[ox-hugo-link DBG] link type: id
[ox-hugo-link DBG] destination: org-roam-file-B.org
[ox-hugo-link DBG] link: (link (:type "id" :path "01579e8c-a90b-4c53-af58-e18ff7877d00" :format bracket :raw-link "id:01579e8c-a90b-4c53-af58-e18ff7877d00" :application nil :search-option nil :begin 160 :end 206 :contents-begin 203 :contents-end 204 :post-blank 0 :parent (paragraph (:begin 160 :end 207 :contents-begin 160 :contents-end 207 :post-blank 1 :post-affiliated 160 :mode nil :granularity nil :parent (section (:begin 1 :end 208 :contents-begin 1 :contents-end 207 :robust-begin 1 :robust-end 205 :post-blank 1 :post-affiliated 1 :mode first-section :granularity nil :parent (org-data (:begin 1 :contents-begin 1 :contents-end 207 :end 208 :robust-begin 67 :robust-end 205 :post-blank 1 :post-affiliated 1 :path "/home/kmodi/stow/pub_dotfiles/emacs/dot-emacs.d/elisp/ox-hugo/test/site/content-org/org-roam/org-roam-file-A.org" :mode org-data :ID "1e8ccec9-735d-41d0-b0cf-143d9c3e965d" :CATEGORY "org-roam-file-A" :granularity nil) #4)) (keyword (:key "TITLE" :value "A" :begin 68 :end 79 :post-blank 1 :post-affiliated 68 :mode nil :granularity nil :parent #4)) (keyword (:key "FILETAGS" :value "org-roam @org-id" :begin 79 :end 109 :post-blank 1 :post-affiliated 79 :mode nil :granularity nil :parent #4)) (paragraph (:begin 109 :end 160 :contents-begin 109 :contents-end 159 :post-blank 1 :post-affiliated 109 :mode nil :granularity nil :parent #4) (link (:type "https" :path "//github.com/kaushalmodi/ox-hugo/issues/500" :format plain :raw-link "https://github.com/kaushalmodi/ox-hugo/issues/500" :application nil :search-option nil :begin 109 :end 158 :contents-begin nil :contents-end nil :post-blank 0 :parent #5)) #("
" 0 1 (:parent #5))) #2)) #0 #("
" 0 1 (:parent #2)))) #("B" 0 1 (:parent #0)))
[org-hugo-link DBG] link destination elem type: plain-text
[ox-hugo-link DBG] plain-text path: org-roam-file-B.md
[ox-hugo-link DBG] plain-text org-id anchor: ""
```

Compare above with the messages you see.

**Comment by zeeros** [comment]
I'm sorry, I don't think I'm doing it right. In `*Messages*` I'm seeing just the following output

```
Loading /home/eros/Desktop/example.el (source)...
Creating LaTeX previews in buffer... done.
[ox-hugo] Exporting ‘A’ (org-roam-file-A.org)
org-babel-exp process emacs-lisp at position 208...
Creating LaTeX previews in buffer... done.
Creating LaTeX previews in buffer... done.
Saving file /home/eros/Desktop/.packages/ox-hugo/test/site/content-org/content/org-roam/org-roam-file-A.md...
Wrote /home/eros/Desktop/.packages/ox-hugo/test/site/content-org/content/org-roam/org-roam-file-A.md
user-error: [ox-hugo] example.el: The entire file is attempted to be exported, but it is missing the #+title keyword
```

Is the debug info printed in there?

**Comment by kaushalmodi** [comment]
> I'm seeing just the following output

That means that you are not evaluating the ox-hugo.el version from that debug branch.

1. Clone and check out the debug branch from this repo
    ```
    mkdir -p ~/temp && cd ~/temp
    git clone https://github.com/kaushalmodi/ox-hugo
    cd ox-hugo
    git checkout org-id-path-dbg
    ```
2. Open the `~/temp/ox-hugo/ox-hugo.el` in emacs and do `M-x eval-buffer`
3. Open `~/temp/ox-hugo/test/site/content-org/org-roam/org-roam-file-A.org` in emacs
4. Eval: `(setq org-id-extra-files (directory-files-recursively default-directory "\.org$"))`
5. Export that file: `C-c C-e H H`

You should see the debug messages in the \*Messages\* buffer.

**Comment by zeeros** [comment]
Thanks for the walk-through, this is what I get now in the *Messages* buffer

```
Evaluating...
("/home/eros/temp/ox-hugo/test/site/content-org/org-roam/org-roam-file-A.org" "/home/eros/temp/ox-hugo/test/site/content-org/org-roam/org-roam-file-B.org")
You can run the command ‘pp-eval-expression’ with M-x p-e-e RET
("/home/eros/temp/ox-hugo/test/site/content-org/org-roam/org-roam-file-A.org" "/home/eros/temp/ox-hugo/test/site/content-org/org-roam/org-roam-file-B.org")
[ox-hugo] Exporting ‘A’ (org-roam-file-A.org)
org-babel-exp process emacs-lisp at position 208...
Creating LaTeX previews in buffer... done.
[ox-hugo-link DBG] raw-path 1: //github.com/kaushalmodi/ox-hugo/issues/500
setq: Symbol’s function definition is void: org-blackfriday--url-sanitize-maybe
```

**Comment by kaushalmodi** [comment]
>setq: Symbol’s function definition is void: org-blackfriday--url-sanitize-maybe

That's an error. I am not getting that error. The debug messages of interest would be coming after that. 

You were not seeing any error yesterday, so I am confused.

**Comment by kaushalmodi** [comment]
I realized I missed one step in my instructions. I have updated the above instructions now. Please try again..You also need to eval the ox-blackfriday.el from the cloned directory.

**Comment by zeeros** [comment]
Got it, this is now the output.

```
[ox-hugo-link DBG] raw-path 1: //github.com/kaushalmodi/ox-hugo/issues/500
[ox-hugo-link DBG] raw-path 2: //github.com/kaushalmodi/ox-hugo/issues/500
[ox-hugo-link DBG] raw-path 1: 01579e8c-a90b-4c53-af58-e18ff7877d00
[ox-hugo-link DBG] raw-path 2: 01579e8c-a90b-4c53-af58-e18ff7877d00
[ox-hugo-link DBG] link type: id
[ox-hugo-link DBG] destination: org-roam-file-B.org
[ox-hugo-link DBG] link: (link (:type "id" :path "01579e8c-a90b-4c53-af58-e18ff7877d00" :format bracket :raw-link "id:01579e8c-a90b-4c53-af58-e18ff7877d00" :application nil :search-option nil :begin 160 :end 206 :contents-begin 203 :contents-end 204 :post-blank 0 :parent (paragraph (:begin 160 :end 207 :contents-begin 160 :contents-end 207 :post-blank 1 :post-affiliated 160 :parent (section (:begin 1 :end 208 :contents-begin 1 :contents-end 207 :post-blank 1 :post-affiliated 1 :parent (org-data nil #4)) (keyword (:key "TITLE" :value "A" :begin 68 :end 79 :post-blank 1 :post-affiliated 68 :parent #4)) (keyword (:key "FILETAGS" :value "org-roam @org-id" :begin 79 :end 109 :post-blank 1 :post-affiliated 79 :parent #4)) (paragraph (:begin 109 :end 160 :contents-begin 109 :contents-end 159 :post-blank 1 :post-affiliated 109 :parent #4) (link (:type "https" :path "//github.com/kaushalmodi/ox-hugo/issues/500" :format plain :raw-link "https://github.com/kaushalmodi/ox-hugo/issues/500" :application nil :search-option nil :begin 109 :end 158 :contents-begin nil :contents-end nil :post-blank 0 :parent #5)) #("
" 0 1 (:parent #5))) #2)) #0 #("
" 0 1 (:parent #2)))) #("B" 0 1 (:parent #0)))
[org-hugo-link DBG] link destination elem type: plain-text
[ox-hugo-link DBG] plain-text path: org-roam-file-B.md
Creating LaTeX previews in buffer... done.
[ox-hugo-link DBG] plain-text org-id anchor: ""
Saving file /home/zeeros/temp/ox-hugo/test/site/content/org-roam/org-roam-file-A.md...
Wrote /home/zeeros/temp/ox-hugo/test/site/content/org-roam/org-roam-file-A.md
```

And now the md file is also correctly exported.

```
+++
title = "A"
tags = ["org-roam"]
categories = ["org-id"]
draft = false
+++

<https://github.com/kaushalmodi/ox-hugo/issues/500>

[B]({{<relref "org-roam-file-B.md#" >}})
```

I'll try to walk back from this configuration and try to understand when/where things go wrong

**Comment by kaushalmodi** [comment]
@zeeros Whether you are managing your emacs config yourself or using a configuration system like Doom, make sure that it's configured correctly so that it always fetches the latest version of ox-hugo and not a _pinned_ version.

**Comment by zeeros** [comment]
Here the debug messages when the path is wrong

```
[1/2] org2md org/org-roam-file-A.org
dbg org-id-extra-files: ("/home/zeeros/temp/ox-hugo1/org/org-roam-file-B.org" "/home/zeeros/temp/ox-hugo1/org/org-roam-file-A.org")
[ox-hugo] Exporting ‘A’ (org-roam-file-A.org)
[ox-hugo-link DBG] raw-path 1: //github.com/kaushalmodi/ox-hugo/issues/500
[ox-hugo-link DBG] raw-path 2: //github.com/kaushalmodi/ox-hugo/issues/500
[ox-hugo-link DBG] raw-path 1: 01579e8c-a90b-4c53-af58-e18ff7877d00
[ox-hugo-link DBG] raw-path 2: 01579e8c-a90b-4c53-af58-e18ff7877d00
[ox-hugo-link DBG] link type: id
[ox-hugo-link DBG] destination: ../../ox-hugo/org/org-roam-file-B.org
[ox-hugo-link DBG] link: (link (:type "id" :path "01579e8c-a90b-4c53-af58-e18ff7877d00" :format bracket :raw-link "id:01579e8c-a90b-4c53-af58-e18ff7877d00" :application nil :search-option nil :begin 160 :end 206 :contents-begin 203 :contents-end 204 :post-blank 0 :parent (paragraph (:begin 160 :end 207 :contents-begin 160 :contents-end 207 :post-blank 1 :post-affiliated 160 :parent (section (:begin 1 :end 208 :contents-begin 1 :contents-end 207 :post-blank 1 :post-affiliated 1 :parent (org-data nil #4)) (keyword (:key "TITLE" :value "A" :begin 68 :end 79 :post-blank 1 :post-affiliated 68 :parent #4)) (keyword (:key "FILETAGS" :value "org-roam @org-id" :begin 79 :end 109 :post-blank 1 :post-affiliated 79 :parent #4)) (paragraph (:begin 109 :end 160 :contents-begin 109 :contents-end 159 :post-blank 1 :post-affiliated 109 :parent #4) (link (:type "https" :path "//github.com/kaushalmodi/ox-hugo/issues/500" :format plain :raw-link "https://github.com/kaushalmodi/ox-hugo/issues/500" :application nil :search-option nil :begin 109 :end 158 :contents-begin nil :contents-end nil :post-blank 0 :parent #5)) #("
" 0 1 (:parent #5))) #2)) #0 #("
" 0 1 (:parent #2)))) #("B" 0 1 (:parent #0)))
[org-hugo-link DBG] link destination elem type: plain-text
[ox-hugo-link DBG] plain-text path: ../../ox-hugo/org/org-roam-file-B.md
[ox-hugo-link DBG] plain-text org-id anchor: ""
[2/2] org2md org/org-roam-file-B.org
dbg org-id-extra-files: ("/home/zeeros/temp/ox-hugo1/org/org-roam-file-B.org" "/home/zeeros/temp/ox-hugo1/org/org-roam-file-A.org")
[ox-hugo] Exporting ‘B’ (org-roam-file-B.org)
[ox-hugo-link DBG] raw-path 1: //github.com/kaushalmodi/ox-hugo/issues/500
[ox-hugo-link DBG] raw-path 2: //github.com/kaushalmodi/ox-hugo/issues/500
```

**Comment by kaushalmodi** [comment]
```
[ox-hugo-link DBG] link type: id
[ox-hugo-link DBG] destination: ../../ox-hugo/org/org-roam-file-B.org
```

That means that the `org-export-resolve-id-link` is returning the incorrect path.

```org
      (let ((destination (if (string= type "fuzzy")
                             (org-export-resolve-fuzzy-link link info)
                           (org-export-resolve-id-link link info))))
        ;; (message "[org-hugo-link DBG] link type: %s" type)
        ;; (message "[org-hugo-link DBG] destination: %s" destination)
```

So the issue seems related to something on your machine or your config.

Can you attempt to `edebug` that function to understand why it is returning that value? Sorry, I cannot help much with that. 

Here are some useful guides:

- https://endlessparentheses.com/debugging-emacs-lisp-part-1-earn-your-independence.html
- https://endlessparentheses.com/debugging-elisp-part-2-advanced-topics.html

(I had learned to do edebug after reading these.)

**Comment by zeeros** [comment]
I'm evaluating the following code

```
(load "ox-blackfriday")
(load "ox-hugo")

(require 'find-lisp)
(require 'ox-hugo)

(with-current-buffer (find-file-noselect "org/org-roam-file-A.org")
;;(with-current-buffer (find-file-noselect "org/org-roam-file-A.org")
  (setq org-hugo-base-dir "..")
  (let ((org-id-extra-files (find-lisp-find-files "." "\.org$")))
    (org-hugo-export-wim-to-md)))

```

I can't make much sense of the execution other than seeing that in fact the id is not found in the current parse tree, and it looks for external files.

![image](https://user-images.githubusercontent.com/1713464/148285562-4fa4956a-85ec-40cf-920b-ba178c2f6bbb.png)

**Comment by kaushalmodi** [comment]
It looks like when that id gets saved to `.org-id-locations` (note the dot in the beginning), it's getting saved as that path?

You will find that file in your "emacs config dir" (usually `~/.emacs.d/`). For me the paths for the 2 .org files in this test are:

```el
 ("~/stow/pub_dotfiles/emacs/dot-emacs.d/elisp/ox-hugo/test/site/content-org/org-roam/org-roam-file-B.org" "01579e8c-a90b-4c53-af58-e18ff7877d00")
 ("~/stow/pub_dotfiles/emacs/dot-emacs.d/elisp/ox-hugo/test/site/content-org/org-roam/org-roam-file-A.org" "1e8ccec9-735d-41d0-b0cf-143d9c3e965d"))
```

**Comment by kaushalmodi** [comment]
so now I think.. that initially you had those Org files at a different location and the id/path association got saved there since then. And then you moved the files. So the exported path is already relative to that original path.

You can delete that `.org-id-locations` file as it will anyways get regenerated. Once you delete it, I think this issue should be fixed for you.

**Comment by zeeros** [comment]
Yes, in fact now I can make it work with both `/home/zeeros/temp/ox-hugo` and `/home/zeeros/temp/ox-hugo1` by deleting the `.org-id-locations` file.

However now I'm facing another problem: my project would be hosted in a partition different from where I've installed emacs `(/home/zeeros/.emacs.d/)`, and the trick of deleting the `.org-id-locations` doesn't help in this case. It looks like the path is resolved in a relative way to where emacs is installed wrt the project folder in the other partition.

In this case the `.org-id-locations` file is the following

```
(("/data/Documents/rnotes/org/org-roam-file-A.org" "1e8ccec9-735d-41d0-b0cf-143d9c3e965d") ("/data/Documents/rnotes/org/org-roam-file-B.org" "01579e8c-a90b-4c53-af58-e18ff7877d00"))
```

And the path is resolved as below

```
+++
title = "A"
author = ["eros"]
tags = ["org-roam"]
categories = ["org-id"]
draft = false
+++

<https://github.com/kaushalmodi/ox-hugo/issues/500>

[B]({{<relref "../../../../../data/Documents/rnotes/org/org-roam-file-B.md#" >}})
```

**Comment by kaushalmodi** [comment]
hmm.. I have attempted at patching an internal function in Org mode.

1. Copy below function to a temp.el file
2. Do `M-x eval-buffer`
3. Then try re-exporting using ox-hugo and see if the issue is fixed

```el
(defun org-export-resolve-id-link (link info)
  "Return headline referenced as LINK destination.

INFO is a plist used as a communication channel.

Return value can be the headline element matched in current parse
tree or a file name.  Assume LINK type is either \"id\" or
\"custom-id\".  Throw an error if no match is found."
  (let ((id (org-element-property :path link)))
    ;; First check if id is within the current parse tree.
    (or (org-element-map (plist-get info :parse-tree) 'headline
	  (lambda (headline)
	    (when (or (equal (org-element-property :ID headline) id)
		      (equal (org-element-property :CUSTOM_ID headline) id))
	      headline))
	  info 'first-match)
	;; Otherwise, look for external files.
    ;; (cdr (assoc id (plist-get info :id-alist)))   ;<---- original
    (file-relative-name (cdr (assoc id (plist-get info :id-alist))))
	(signal 'org-link-broken (list id)))))
```

If that fixes the problem:

1. I will think of adding a workaround for this to ox-hugo
2. But please also report this bug on the Org mode mailing list: emacs-orgmode@gnu.org

**Comment by zeeros** [comment]
I've been trying to call the modified function, but the path is still wrong

```
Loading ox-blackfriday...done
Loading ox-hugo...done
[ox-hugo] Exporting ‘A’ (org-roam-file-A.org)
org-babel-exp process emacs-lisp at position 208...
Creating LaTeX previews in buffer... done.
CALLING MODIFIED org-export-resolve-id-link
Creating LaTeX previews in buffer... done.
Saving file /data/Documents/ox-hugo1/content/posts/org-roam-file-A.md...
Wrote /data/Documents/ox-hugo1/content/posts/org-roam-file-A.md
```

```
+++
title = "A"
draft = false
+++

<https://github.com/kaushalmodi/ox-hugo/issues/500>

[B]({{<relref "../../../../../data/Documents/ox-hugo1/org/org-roam-file-B.md#" >}})
```

This is the generated `.org-id-locations` file

```
(("/data/Documents/ox-hugo1/org/org-roam-file-B.org" "01579e8c-a90b-4c53-af58-e18ff7877d00") ("/data/Documents/ox-hugo1/org/org-roam-file-A.org" "1e8ccec9-735d-41d0-b0cf-143d9c3e965d"))
```

By manually changing the file as follows I get the path is correctly exported

```
(("~/Documents/ox-hugo1/org/org-roam-file-B.org" "01579e8c-a90b-4c53-af58-e18ff7877d00") ("~/Documents/ox-hugo1/org/org-roam-file-A.org" "1e8ccec9-735d-41d0-b0cf-143d9c3e965d"))
```

I have to say that yesterday, after several attempts, everything seemed to work correctly even with the project beeing in `/data/Documents/rnotes/`. It happened after I moved the `build.py` code into a code block in a org file and evaluated the code from there. However, now I've been trying your new patched function in `/data/Documents/ox-hugo1/` and somehow we are back to the problem, I've been not been able yet to understand why and how to make it work again.

**Comment by kaushalmodi** [comment]
Glad to see that you got this working, even with a workaround. 

> To be clear, ~/Documents/ is a soft link to /data/Documents/ and I guess this case is not well managed.

Can you please email that issue to the Org mailing list? This issue should be reproduced even without ox-hugo.

**Comment by zeeros** [comment]
Yes, and thank you for the support 🙏

**Comment by kaushalmodi** [comment]
@zeeros Turns out that the behavior you are seeing is expected and even documented, and it stems from the `file-relative-name` function in emacs: https://www.gnu.org/software/emacs/manual/html_node/elisp/Relative-File-Names.html

**Comment by kaushalmodi** [comment]
So may be the symlinking solution you have is the most robust way to do this.

**Comment by zeeros** [comment]
If it can be useful to anybody else in the future, I display my temporary fix. I've added to my publish procedure this `.el` that trims the path to leave just the filename and the extension.

I'm sure it can be dealt with a better regexp formulation in elisp since its kind of hard coded (didn't managed to make it better yet), but at least it gives a general idea of the approach. So just during the publishing, I'm overriding the `org-export-resolve-id-link ` function to trim the path.

```
(defun replace-in-string (what with in)
  (replace-regexp-in-string (regexp-quote what) with in nil 'literal))

(defun fix-doc-path (path)
  (replace-in-string "data/Documents/rnotes/org/" "" (replace-in-string "../" "" path)))

(defun org-export-resolve-id-link (link info)
  "Return headline referenced as LINK destination.

INFO is a plist used as a communication channel.

Return value can be the headline element matched in current parse
tree or a file name.  Assume LINK type is either \"id\" or
\"custom-id\".  Throw an error if no match is found."
  (let ((id (org-element-property :path link)))
    ;; First check if id is within the current parse tree.
    (or (org-element-map (plist-get info :parse-tree) 'headline
	  (lambda (headline)
	    (when (or (equal (org-element-property :ID headline) id)
		      (equal (org-element-property :CUSTOM_ID headline) id))
	      headline))
	  info 'first-match)
	;; Otherwise, look for external files.
    ;; (cdr (assoc id (plist-get info :id-alist)))   ;<---- original
    (fix-doc-path (cdr (assoc id (plist-get info :id-alist))))
    (signal 'org-link-broken (list id)))))
```

**Comment by harshasomisetty** [comment]
I'm having a very similar where when I export, the relrefs are relative and not local. I 

I ran the code in https://github.com/kaushalmodi/ox-hugo/issues/500#issuecomment-1005156294, and it seems to work, and I got the following debug messages

`
("/Users/harshasomisetty/temp/ox-hugo/test/site/content-org/org-roam/org-roam-file-A.org" "/Users/harshasomisetty/temp/ox-hugo/test/site/content-org/org-roam/org-roam-file-B.org")
[ox-hugo] Exporting ‘A’ (org-roam-file-A.org)
org-babel-exp process emacs-lisp at position 208...
167 files scanned, 163 files contains IDs, and 168 IDs found.
Saving file /Users/harshasomisetty/temp/ox-hugo/test/site/content/org-roam/org-roam-file-A.md...
Wrote /Users/harshasomisetty/temp/ox-hugo/test/site/content/org-roam/org-roam-file-A.md
Reverting buffer ‘.org-id-locations’.`

However, when I move to my own roam files, execute that lisp code for the extra files, then do org-export to hugo, the relref error stil occurs. I'm a bit unsure what to do next, would you be able to ehlp

**Comment by harshasomisetty** [comment]
@zeeros would you be able to explain how you're using this lisp code with the previous publish.el? Seeing the full workflow would be really helpful

**Comment by kaushalmodi** [comment]
@harshasomisetty Can you post a snippet of the generated problematic Markdown and related Org source?

---

> I ran the code in #500 (comment), 

It doesn't make sense.. I am seeing no dbg messages being printed. Did you follow all the steps in that comment?

---

Also use triple-backquotes for code blocks.. like this:

````
```
code line 1
code line 2
```
````

**Comment by kaushalmodi** [comment]
@zeeros 

> If it can be useful to anybody else in the future,

Thanks for sharing. You can probably make it quite a bit shorter by using `:around` advice. See https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html for some helpful short examples.

**Comment by kaushalmodi** [comment]
@harshasomisetty Also, do you have your emacs config and Org files on separate mounts/devices/partitions? like one under `/home/..` and another under `/data/..`? If not, can you create a new ticket?

**Comment by harshasomisetty** [comment]
@kaushalmodi ah sorry about that, no I don't so I'll create a new ticket

**Comment by kaushalmodi** [comment]
@harshasomisetty Thanks! Please  follow the issue template (that includes providing a minimum example of Org file that can reproduce the issue you are seeing).

**Comment by zeeros** [comment]
> @zeeros
> 
> > If it can be useful to anybody else in the future,
> 
> Thanks for sharing. You can probably make it quite a bit shorter by using `:around` advice. See https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html for some helpful short examples.

Thanks for the tip, I've edited the comment with the code accordingly

**Comment by dorneanu** [comment]
Hi,

I'm not sure if I should create a new issue. I'm having /almost/ the same problem: 

- I have one `org-roam-directory` (`/cs/priv/repos/roam/org`)
- there I have 2 subfolders
   - `books/`: Contains books related ORG files
   - `topics/`: Contains multiple ORG files related to different topics

I use this `publish.el` inside `/cs/priv/repos/roam` to export (via ox-hugo) to markdown (I'm using a similar setup like [this one](https://github.com/jethrokuan/braindump)): 

```
(defun brainfck/publish (file)
  (with-current-buffer (find-file-noselect file)
    (setq-local org-hugo-base-dir "/cs/priv/repos/roam")
    (setq-local org-hugo-section "posts")
    (setq-local org-export-with-tags nil)
    (setq-local org-export-with-broken-links t)
    (setq-local org-agenda-files nil)
    (let ((org-id-extra-files (directory-files-recursively org-roam-directory "\.org$")))
      (org-hugo-export-wim-to-md))))
```

I run: 

```
$ python build.py
```

and afterwords I can see markdown generated files in `content/posts/`. 

Now the problem...

Let's say in a book ORG file (e.g. `books/a.org`) I link to a topic (e.g. `topics/b.org`), This is what I get: 

```
$ cat content/posts/a.md
...
on [b]({{< relref "../../topics/b.md" >}})
```

`a.md` and `b.md` are both in `content/posts/`. Using [this workaround](https://github.com/kaushalmodi/ox-hugo/issues/500#issuecomment-1006674469) it converts only to:

```
$ cat content/posts/a.md
...
on [b]({{< relref "b.md" >}})
```

But this workaround feels somehow "hacky". Is there anything else I need to consider when working with subdirectories inside a org-roam directory (and exporting using `ox-hugo`)?

Thanks in advance.

**Comment by holmus-hiddyn** [comment]
@dorneanu I came across this as well when doing the following doomscript:

```
#!/usr/bin/env doomscript

(require 'find-lisp)

(defcli! export-notes (&args files)
  (require 'doom-start)          ; load your user config
  (dolist (file files)           ; supports multiple files, if you want
    (find-file file)             ; open an org file
    (setq org-hugo-section "notes"
          org-hugo-base-dir "/Users/user/Projects/brain"
          citeproc-org-org-bib-header "* Bibliography\n<ol class=\"biblio-list\">"
          citeproc-org-org-bib-footer "</ol>")
        (let ((org-id-extra-files (org-roam-list-files)))
        (org-hugo-export-wim-to-md))))

(run! "export-notes" (cdr (member "--" argv)))
```

Did you ever happen to find a workaround? Haven't had any luck so far, my relrefs are all using those relative links to other subdirectories.
